// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearLogs() {
  return window['go']['main']['App']['ClearLogs']();
}

export function IsFirstRun() {
  return window['go']['main']['App']['IsFirstRun']();
}

export function GetAvailableLocales() {
  return window['go']['main']['App']['GetAvailableLocales']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetImagePreview() {
  return window['go']['main']['App']['GetImagePreview']();
}

export function GetLocale(arg1) {
  return window['go']['main']['App']['GetLocale'](arg1);
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetPrinters() {
  return window['go']['main']['App']['GetPrinters']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function PrintNow() {
  return window['go']['main']['App']['PrintNow']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SelectImage() {
  return window['go']['main']['App']['SelectImage']();
}
