// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearLogs(): Promise<void>;

export function IsFirstRun(): Promise<boolean>;

export function GetAvailableLocales(): Promise<Array<{ code: string; name: string }>>;

export function GetConfig(): Promise<{
  enabled: boolean;
  printerName: string;
  paperSource: number;
  intervalDays: number;
  imagePath: string;
  language: string;
  lastPrintTime: string;
}>;

export function GetImagePreview(): Promise<string>;

export function GetLocale(lang: string): Promise<Record<string, any>>;

export function GetLogs(): Promise<string>;

export function GetPrinters(): Promise<string[]>;

export function GetStatus(): Promise<{
  enabled: boolean;
  printerReady: boolean;
  lastPrint: string;
  nextPrint: string;
  statusText: string;
  statusLevel: string;
}>;

export function PrintNow(): Promise<void>;

export function SaveConfig(config: {
  enabled: boolean;
  printerName: string;
  paperSource: number;
  intervalDays: number;
  imagePath: string;
  language: string;
}): Promise<void>;

export function SelectImage(): Promise<string>;
